In [ ]:
import pandas as pd
from sqlalchemy import create_engine

# -----------------------------------------------------------
# 1. DB 연결 설정
# -----------------------------------------------------------
# [옵션 A] 개발용 SQLite (파일로 저장됨, 별도 설치 불필요)
db_connection_str = 'sqlite:///hscode_db.sqlite3'

# [옵션 B] 실제 서비스용 MySQL/MariaDB 예시
# db_connection_str = 'mysql+pymysql://사용자ID:비밀번호@localhost/데이터베이스이름'

# 엔진 생성
db_connection = create_engine(db_connection_str)
conn = db_connection.connect()

# -----------------------------------------------------------
# 2. [테이블 1] 관세율 마스터 테이블 (df_desc_base)
# -----------------------------------------------------------
# (1) 컬럼명 영문 변환 (DB 표준)
df_master_sql = df_desc_base.rename(columns={
    '코드유효값': 'tariff_code',
    '설명': 'description',
    '적용순위': 'priority'
})

# (2) 필요한 컬럼만 선택 (혹시 불필요한 게 섞여있을 수 있으니)
df_master_sql = df_master_sql[['tariff_code', 'description', 'priority']]

# (3) 중복 제거 (PK가 될 컬럼이므로 중복 있으면 에러 남)
df_master_sql = df_master_sql.drop_duplicates(subset=['tariff_code'])

# (4) DB에 저장 (to_sql)
# if_exists='replace': 테이블이 이미 있으면 지우고 새로 만듦 (초기 구축 시 편리)
# index=False: 판다스의 숫자 인덱스(0,1,2...)는 저장 안 함
df_master_sql.to_sql(name='tariff_master', con=db_connection, if_exists='replace', index=False)

print("✅ 'tariff_master' 테이블 저장 완료!")


# -----------------------------------------------------------
# 3. [테이블 2] HS코드 매핑 테이블 (데이터 1번)
# -----------------------------------------------------------
# 가정: df_hs 라는 데이터프레임에 10자리 HS코드와 관세코드가 있다고 가정
# 예: df_hs = pd.DataFrame({'hs코드':['0101101000', ...], '관세코드':['A', ...], '세율':[8, ...]})

# (1) 컬럼명 영문 변환
# df_hs_sql = df_hs.rename(columns={
#     'hs코드': 'hscode',
#     '관세코드': 'tariff_code',
#     '세율': 'rate'
# })

# (2) DB에 저장
# df_hs_sql.to_sql(name='hs_tariff_map', con=db_connection, if_exists='replace', index=False)
# print("✅ 'hs_tariff_map' 테이블 저장 완료!")

In [2]:
import pandas as pd
import sqlite3

rank = pd.read_csv('tariff_ranking.csv')
mapp = pd.read_csv('tariff_mapping.csv')
display(rank.head(), mapp.head())

  tariff_code   tariff_desc  ranking
0           A          기본세율        7
1          A1     기본세율(선택1)        7
2           B          잠정세율        6
3           C       WTO협정세율        3
4          C1  WTO협정세율(선택1)        3

      hscode tariff_code  tariff_rate  rate_start_date  rate_end_date
0  101211000           A          0.0         20250101       20251231
1  101219000           A          8.0         20250101       20251231
2  101291000           A          8.0         20250101       20251231
3  101299000           A          8.0         20250101       20251231
4  101300000           A          8.0         20250101       20251231

In [3]:
# 1. DB 연결 
from sqlalchemy import create_engine
# 이 파일(DB) 하나에 다 넣을 겁니다.
db_connection = create_engine('sqlite:///tariff_db.sqlite3') 

# -------------------------------------------------------

# 2. 첫 번째 CSV (관세율 마스터 정보) 넣기
# name='tariff_master' -> 이 이름표(테이블)로 저장됨
rank.to_sql(name='tariff_ranking', con=db_connection, if_exists='replace', index=False)

# 3. 두 번째 CSV (HS코드 매핑 정보) 넣기
# name='hs_tariff_map' -> 다른 이름표(테이블)로 저장됨
# *중요: con은 위랑 똑같은 db_connection을 씁니다!
mapp.to_sql(name='tariff_mapping', con=db_connection, if_exists='replace', index=False)

# -------------------------------------------------------
print("✅ 하나의 DB 파일에 두 개의 테이블이 저장되었습니다!")

✅ 하나의 DB 파일에 두 개의 테이블이 저장되었습니다!

In [8]:
target_hscode = '8542311000'
sql = f"""
SELECT 
    m.tariff_code   AS 관세율코드,  -- m(매핑테이블)의 tariff_code 컬럼
    r.tariff_desc   AS 관세설명,    -- r(랭킹테이블)의 description 컬럼
    m.tariff_rate   AS 관세율,
    r.ranking       AS 적용순위
FROM 
    tariff_mapping AS m             -- [핵심] 실제 테이블명은 hs_tariff_map이지만, 난 'm'이라 부르겠다!
LEFT JOIN 
    tariff_ranking AS r             -- [핵심] 실제 테이블명은 tariff_master지만, 난 'r'이라 부르겠다!
    ON m.tariff_code = r.tariff_code
WHERE 
    m.hscode = '8542311000'        -- 검색할 HS코드
ORDER BY 
    r.ranking ASC, 
    m.tariff_rate ASC;
"""

# 쿼리 실행 및 결과 보기
df_result = pd.read_sql(sql, db_connection)

print(f"--- HS Code [{target_hscode}] 조회 결과 ---")
print(df_result)

--- HS Code [8542311000] 조회 결과 ---
     관세율코드                     관세설명  관세율  적용순위
0     FAS1       한ㆍ아세안 FTA협정세율(선택1)  0.0     2
1     FAU1        한ㆍ호주 FTA협정세율(선택1)  0.0     2
2     FCA1       한ㆍ캐나다 FTA협정세율(선택1)  0.0     2
3     FCL1         한ㆍ칠레FTA협정세율(선택1)  0.0     2
4     FCN1        한ㆍ중국 FTA협정세율(선택1)  0.0     2
5     FCO1       한ㆍ콜롬비아FTA협정세율(선택1)  0.0     2
6     FEF1      한ㆍEFTA FTA협정세율(선택1)  0.0     2
7     FEU1        한ㆍEU FTA협정세율(선택1)  0.0     2
8     FIN1        한ㆍ인도 FTA협정세율(선택1)  0.0     2
9     FNZ1      한ㆍ뉴질랜드 FTA협정세율(선택1)  0.0     2
10    FPE1        한ㆍ페루 FTA협정세율(선택1)  0.0     2
11    FSG1       한ㆍ싱가포르FTA협정세율(선택1)  0.0     2
12    FTR1        한ㆍ터키 FTA협정세율(선택1)  0.0     2
13    FUS1        한ㆍ미 FTA 협정세율(선택1)  0.0     2
14    FVN1       한ㆍ베트남 FTA협정세율(선택1)  0.0     2
15       C                  WTO협정세율  0.0     3
16  FCECR1  한ㆍ중미 FTA협정세율_코스타리카(선택1)  0.0     3
17  FCEHN1   한ㆍ중미 FTA협정세율_온두라스(선택1)  0.0     3
18  FCENI1   한ㆍ중미 FTA협정세율_니카라과(선택1)  0.0     3
19  FCEPA1    한ㆍ중미 FTA협정세율_파나마(선택1)  0.0     3
20  FCESV1  한ㆍ중미 FTA협정세율_엘살바도르(선택1)  0.0     3
21    FGB1        한ㆍ영국 FTA협정세율(선택1)  0.0     3
22    FID1        한ㆍ인도네시아 CEPA(선택1)  0.0     3
23    FIL1          한ㆍ이스라엘 FTA(선택1)  0.0     3
24    FKH1          한ㆍ캄보디아 FTA(선택1)  0.0     3
25    FPH1           한ㆍ필리핀 FTA(선택1)  0.0     3
26  FRCAS1        RCEP협정세율_아세안(선택1)  0.0     3
27  FRCAU1         RCEP협정세율_호주(선택1)  0.0     3
28  FRCCN1         RCEP협정세율_중국(선택1)  0.0     3
29  FRCJP1         RCEP협정세율_일본(선택1)  0.0     3
30  FRCNZ1       RCEP협정세율_뉴질랜드(선택1)  0.0     3
31       R                  최빈국특혜관세  0.0     5
32       A                     기본세율  0.0     7
33       U                      북한산  0.0     7